#!/bin/bash

source /host-environment

DOMAIN=$(etcdctl --peers http://$COREOS_PRIVATE_IPV4:4001 get /flitter/domain)

if [ -z "$DOMAIN" ]; then
	echo "No domain set"
	killall runsvdir
fi

/usr/local/bin/havok -host-ip $COREOS_PRIVATE_IPV4 -root-domain $DOMAIN -names 'app-(\w+)|flitter-lagann' -etcd-machines http://$COREOS_PRIVATE_IPV4:4001
