#!/bin/sh

DOMAIN=$(etcdctl get /flitter/domain)

if [ -z "$DOMAIN" ]; then
	echo "No domain set"
	killall runsvdir
fi

source /host-environment

/usr/local/bin/havok -host-ip $COREOS_PRIVATE_IPV4 -root-domain $DOMAIN -names 'app-(\w+)' -etcd-machines http://$COREOS_PRIVATE_IPV4:4001
